Add mg to contribs
covidgreen/covid-green-infra pull request #2
Opened 2020-08-05 04:16 UTC by segfault

adding myself to the contributor list

2020-08-05 14:41 UTC, jasnell commented
@segfault ... Really just a formality, but before adding to contributors, you'll need a formal nomination to be added as a @covidgreen/members from another existing member, posted as an issue with no objections from other members. See https://github.com/covidgreen/covid-green-backend-api/issues/7 as an example. This PR can't land until that is done. Once you've gone through the nomination, I can add you to the members team. Will mark this PR "changes required" until that goes through.

2020-08-05 14:41 UTC, jasnell requested changes
Pending @covidgreen/members nomination

2020-08-05 14:48 UTC, jasnell commented
Nomination issue: https://github.com/covidgreen/covid-green-infra/pull/2

2020-08-11 09:27 UTC, dgonzalez approved these changes

2020-08-11 09:31 UTC, dgonzalez commented
This is +1 from me as well

2020-08-11 14:25 UTC, jasnell commented on monitoring.tf
> -# #########################################
Unrelated change?

2020-08-12 14:29 UTC, dgonzalez commented on monitoring.tf
> -# #########################################
no, it is good.

2020-08-12 14:29 UTC, merged

2020-08-12 14:29 UTC, dgonzalez commented
Welcome!

2020-08-12 14:29 UTC, dgonzalez commented on monitoring.tf
> -# #########################################
no, it is good.